### ISSUE TITLE
Arduino IDE from Windows Store incompatible with 3.0.0 (was: New Arduino Error compiling with ESP8266 3.0.0)

### ISSUE THREAD

**Issue by thorathome** [esp8266/Arduino#8059]
### Basic Infos

- [X] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [X] I have tested that the issue is present in current master branch (aka latest git).
- [X] I have searched the issue tracker for a similar issue.
- [X] If there is a stack dump, I have decoded it.
- [X] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-12|ESP-01|ESP-07|ESP8285 device|other]
- Core Version:			[3.0.0]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Nodemcu 1.0 and ITEAD Sonoff]
- Flash Mode:			[no idea]
- Flash Size: 		[4MB/1MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[no idea]
- Flash Frequency:	[no idea]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200] (serial upload only)

### Problem Description

After updating to 3.0.0 I get Error compiling for board ... on NodeMCU and on SONOFF. Several other boards exhibit sale behavior. ESP32, other non-8266 platforms work fine.  
 
Reinstalling ESP8266 2.7.4 fixes this issue. Returning to 3.0.0 brings it back. 
I have removed, uninstalled previous versions, completely deleted \packages\ESP8266 directory, still have same problem. 
I am using Arduino IDE Board Manager. 

I am running fine on 2.7.4 now.  

All help welcome. Hope I am not alone on this one.  

Error message extract is below.  

Simple test code looks like this:
```
#define SKETCH_NAME "CLEAR CODE"
#define SERIAL_SPEED 230400

void setup()
{
  Serial.begin ( SERIAL_SPEED );
  delay ( 500 );  
  Serial.println ( "\n\n=======================================" );
  Serial.println ( SKETCH_NAME );  

  Serial.println ( "Setup done." ); 
}


void loop() 
{
  Serial.println ( "CLEAR-CODE Not doing anything" );  
  delay ( 5000 ); 
}

```

### Debug Messages

```
c:\users\thor\dropbox (personal)\my documents tsj\arduinodata\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.0.0-newlib4.0.0-gnu23-48f7b08\xtensa-lx106-elf\include\c++\10.2.0\xtensa-lx106-elf\bits\c++config.h:521:10: fatal error: bits/cpu_defines.h: No such file or directory

  521 | #include <bits/cpu_defines.h>

      |          ^~~~~~~~~~~~~~~~~~~~

```

**Comment by d-a-v** [comment]
It looks like an installation error. Do you have enough space on your installation drive ?
You should try to completely remove the esp8266 arduino installation (also the arduino15 in appdata) and retry.
Also as a general rule of thumb,
- installing software in a dropbox-synchronized (or \*drive or \*cloud sync-ed directories) should be avoided 
- spaces in file names and directorie sometimes (often) lead to issues

Closing as not an issue with the core

**Comment by thorathome** [comment]
**Thanks for your quick reply.** It helped me find the issue.  

It turns out that there is a **behavior difference between the Arduino IDE App from the Windows Store and the Arduino IDE manual download-and-install version from arduino.cc**. The Windows App creates a **folder named Arduino Data in My Documents** to store all the packages, preferences, and other data. The manual download-and-install version from arduino.cc stores this info in AppData\Local\Arduino15. 

For some reason, while ESP8266 core v2.7.4 works fine, the new 3.0.0 fails on compile with my Windows IDE App installation which uses the Arduino Data folder. 

By uninstalling the Windows App IDE completely, (saving and ) clearing out all related folders, and reinstalling using the arduino.cc manual download-and-install version, all the packages and preferences data now reside in the Arduino15 folder. It now compiles fine.  

**True, it's not a core issue.** Something did change with 3.0.0 that impacted me and probably others. Maybe this will help them  

I will post a similar note at arduino.cc. thought you should know. Thanks for all you do.

**Comment by d-a-v** [comment]
Thanks for the feedback! 
We should try to reproduce with the windows store.

**Comment by mobizt** [comment]
I wonder that your **ArduinoData** folder is in the **Dropbox** folder.

The Arduino IDE Windows app data folder should be at **C:\Users\UserName\Documents\ArduinoData** instead of inside OneDrive or Dropbox folder which files access can be failed or denied from other apps or programs.

I guest that most well developed Windows programs and apps should use the environment variables to store or install the temp or settings of app or user data, especially **%HOMEPATH%** **%USERPROFILE%** **%TMP%** **%TEMP%**

Your **HOMEPATH** and **%USERPROFILE%** in system environment variables should be **C:\Users\UserName**, checking by open the command prompt and type **cd %HOMEPATH%** or **cd %USERPROFILE%**

A full list of all the variables can be displayed by opening a Run window (Windows Logo key+R), typing **cmd /k set** and press Enter.

You should found **HOMEPATH=\Users\UserName** and **USERPROFILE=C:\Users\UserName** from the list.

I also use latest Arduino IDE Windows app and ESP8266 core v3.0.0 installed without this path issue. No OneDrive and Dropbox installed in my Windows 10 PC.

**Comment by d-a-v** [comment]
@mobizt is right:
> I guess your issue is due to dropbox.

@thorathome Can you try your windows store installation in another location, and check others @mobizt's suggestions ?

**Comment by thorathome** [comment]
@d-a-v @mobizt 

**OK, Thanks for showing interest in this issue.**  

I did some work for the community. Here is what I did and what I found. 
- I used a Win 10 laptop that had no Arduino IDE installation at all. 
- I looked for trouble without Dropbox involved. 
- I looked for trouble with too-long filename/pathnames.
- I looked for trouble with spaces in pathnames. 

It's none of these. I tried them all. 

What I found was that, **when I had moved the My Documents folder from its default location** (using File Manager), 
- I was able to install Arduino IDE App from Microsoft Store with no problem, 
- was able to install ESP8266 core 3.0.0, with no problem,
- and **was UNABLE to compile an ESP8266 simple sketch.**  

I uninstalled and reinstalled the Windows App Arduino IDE several times with different configurations, 
- eventually found that moving the My Documents folder back to its default location allowed everything to work again, even without reinstalling Windows App Arduino IDE.   

The Windows App Arduino IDE does not create an Arduino15 folder in AppData\local. It does create an ArduinoData folder under My Documents. For some reason, **with the new ESP8266 core, it appears all ESP8266 compiles fail when the My Documents folder has been moved from its default location.** [_When I use the 'standard' Arduino IDE from arduino.cc, it creates the Arduino15 folder in AppData\local and All Is Right With The World._ That has been my workaround to this behavior (bug?).]

I've been programming Arduino for years. This behavior was not an issue with the 2.7.4 ESP8266 or previous ESP8266 cores. As I have also used Dropbox for years, I have long moved my My Documents and other key folders under Dropbox so they get saved. Only with the new ESP8266 core did I run into this problem. I also use the ESP32 core and that has continued to compile without issues. 

I do hope this was helpful. I'm glad I put in the time. Happy to answer questions if any of this isn't clear.

**Comment by mobizt** [comment]
@thorathome 
Can you try to [enable long path length](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd) (> 260 characters) in Windows 10?

**Comment by thorathome** [comment]
@mobizt 
Thanks again. **Used Regedit to enable long path length**. Rebooted. Uninstalled Windows App Arduino IDE. Rebooted. Reinstalled...

**Same issue.  Compiler error message is here**
```

c:\users\a2345678901234567890\thisxandxthatxtoo\documents\arduinodata\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.0.0-newlib4.0.0-gnu23-48f7b08\xtensa-lx106-elf\include\c++\10.2.0\stdlib.h:36,
                 from C:\Users\A2345678901234567890\ThisXAndXThatXToo\Documents\ArduinoData\packages\esp8266\hardware\esp8266\3.0.0\cores\esp8266/Arduino.h:27,
                 from sketch\sketch_may25a.ino.cpp:1:
c:\users\a2345678901234567890\thisxandxthatxtoo\documents\arduinodata\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.0.0-newlib4.0.0-gnu23-48f7b08\xtensa-lx106-elf\include\c++\10.2.0\cstdlib:41:10: fatal error: bits/c++config.h: No such file or directory
   41 | #include <bits/c++config.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board ITEAD Sonoff.

```
Restoring default location of My Documents folder using File Manager restores normal compiler operation. 
Again, I hope this is helpful.

**Comment by Juppit** [comment]
I guess the recommended way to set the location of the folder My Documents is to right-click My Documents, and then click Properties. From here use the Path tab to set the new path.
@thorathome you wrote only 'using File Manager'

**Comment by thorathome** [comment]
Agreed completely @Juppit 

Right click on My Documents folder icon.
Properties.
Location.
Move.

**Comment by Tech-TX** [comment]
I suspect it's similar to a problem I saw on my Win7 desktop installation a few months ago: spaces in the pathnames aren't resolved correctly.

**Comment by earlephilhower** [comment]
Updated the title since the root cause here seems to be something related to the Windows Store IDE vs. the normal one.  I've heard of this on the RPi Pico core (but there the report was related to an issue accessing the serial port and not compilation).

**Comment by earlephilhower** [comment]
The Window store IDE seems to be working just fine as of Arduino 1.8.15.  Please update accordingly.  I was able to install a new copy of the IDE from scratch, on a system with the proper serial port driver installed, and do a simple upload w/o incident.  If you're installing or running from OneDrive, though, that may be the issue and there's not much we can do for it.

![image](https://user-images.githubusercontent.com/11875/127723348-4cf13b2d-4091-4082-8fd9-b7201ddbc6bc.png)

**Comment by thorathome** [comment]
Thanks for spending time on this!
