### ISSUE TITLE
Timezone.h works with esp board 2.3.0 but not for 2.4.0

### ISSUE THREAD

**Issue by tofrnr** [esp8266/Arduino#4383]
hello
why  compiles Timezone.h 
https://github.com/JChristensen/Timezone
with esp board 2.3.0 but not for 2.4.0 ?
perhaps which different lib or board revision?

error messages for 2.4.0 (2.3.0. is fine though) :

D:\Arduino\libraries\Timezone-master\Timezone.cpp:182:20: error: expected primary-expression before ')' token

     t = makeTime(tm);        //first day of the month, or first day of next month for "Last" rules

                    ^

D:\Arduino\libraries\Timezone-master\Timezone.cpp:182:20: error: 'makeTime' was not declared in this scope

D:\Arduino\libraries\Timezone-master\Timezone.cpp:183:43: error: 'weekday' was not declared in this scope

     t += (7 * (w - 1) + (r.dow - weekday(t) + 7) % 7) * SECS_PER_DAY;

                                           ^

D:\Arduino\libraries\Timezone-master\Timezone.cpp:183:57: error: 'SECS_PER_DAY' was not declared in this scope

**Comment by devyte** [comment]
@tofrnr yous issue is for a 3rd party lib, which is in a different repo, so why are you reporting it here?
The lib README in their repo says it requires Arduino Time lib, which after a quick search provides the missing symbols in your errors.
Closing as user error.

**Comment by tofrnr** [comment]
of course the Arduino Time lib is installed and included.

I am reporting it here because this Arduino standard lib works with esp8266 board driver 2.3.0, but it does NOT work with esp8266 board driver 2.4.0 any more.

**Comment by tofrnr** [comment]
update:
I now also reported this  issue here:
https://github.com/JChristensen/Timezone/issues/29
