### ISSUE TITLE
Problem with platform.io and ArduinoOTA (Example BasicOTA.ino)

### ISSUE THREAD

**Issue by chessweb01** [esp8266/Arduino#3020]
The example BasicOTA.ino that illustrates over the air firmware updates of ESP8266 modules compiles with Arduino IDE 1.6.8 but not with Atom/platform.io. 

With the latter I get "error: 'class ArduinoOTAClass' has no member named 'getCommand'". platform.io has an obsolete version of the ArduinoOTA class. On the other hand, Arduino's version is more recent and has a getCommand method.

I'm positive that Atom, platform.io, and all packages are up to date on my computer. I'm working with NodeMCU v1.0.

Work around: 
Locate Arduino's version of the ArduinoOTA class and put it into the local lib folder (lib/ArduinoOTA/ArduinoOTA.h, .cpp) of the platform.io project.

**Comment by devyte** [comment]
@chessweb01 is this still an issue? I know of others using platformio without problems.

**Comment by gschintgen** [comment]
@devyte 
Hi, I'm not the OP but I'd say this is still an issue. I've just done some maintenance on a small project that I started some months ago and tried to remove my local copy of ArduinoOTA in order to reduce deviations from upstream, when I hit this "has no member named 'getCommand'" error. I'd say my Atom / PlatformIO setup is current as of today.

**Comment by devyte** [comment]
Duplicate of #2833 , closing.
