### ISSUE TITLE
WiFi.beginWPSConfig() is Broken since b66ddbf

### ISSUE THREAD

**Issue by onkelfunny** [esp8266/Arduino#1271]
since esp8266/Arduino@b66ddbf the WiFi.beginWPSConfig() is broken.

```
/Arduino/hardware/esp8266com/esp8266/tools/sdk/lib/libcrypto.a(aes-internal-dec.o): In function `aes_decrypt_init':
(.irom0.text+0x134): undefined reference to `Td4s'
collect2: error: ld returned 1 exit status
make: *** [Projekt.elf] Error 1
```

**Comment by igrr** [comment]
Should be fixed by 70cf3c3

**Comment by onkelfunny** [comment]
works fine! thx
