### PR TITLE
restore proper arduino Client:: & Wire:: API

### LINKED ISSUE #5705: TinyGSM example didn't compile with 2.5.0-beta3.
If I try to compile the TinyGSM-example forHttpClient (see file)
[test.ino.txt](https://github.com/esp8266/Arduino/files/2821530/test.ino.txt) rename to .ino.
I got the following errors:
````
In file included from D:\Benutzer\ic-sc\Dokumente\Arduino\libraries\ArduinoHttpClient\src/ArduinoHttpClient.h:8:0,

                 from D:\Benutzer\ic-sc\Dokumente\Arduino\test\test.ino:32:

D:\Benutzer\ic-sc\Dokumente\Arduino\libraries\ArduinoHttpClient\src/HttpClient.h: In member function 'virtual void HttpClient::flush()':

D:\Benutzer\ic-sc\Dokumente\Arduino\libraries\ArduinoHttpClient\src/HttpClient.h:310:50: error: return-statement with a value, in function returning 'void' [-fpermissive]

     virtual void flush() { return iClient->flush(); };

                                                  ^

D:\Benutzer\ic-sc\Dokumente\Arduino\test\test.ino: At global scope:

test:67:15: error: cannot declare variable 'client' to be of abstract type 'TinyGsmSim800::GsmClient'

 TinyGsmClient client(modem);

               ^

In file included from D:\Benutzer\ic-sc\Dokumente\Arduino\libraries\arduino_267956\src/TinyGsmClientSIM808.h:12:0,

                 from D:\Benutzer\ic-sc\Dokumente\Arduino\libraries\arduino_267956\src/TinyGsmClient.h:29,

                 from D:\Benutzer\ic-sc\Dokumente\Arduino\test\test.ino:31:

D:\Benutzer\ic-sc\Dokumente\Arduino\libraries\arduino_267956\src/TinyGsmClientSIM800.h:53:7: note:   because the following virtual functions are pure within 'TinyGsmSim800::GsmClient':

 class GsmClient : public Client

       ^

In file included from D:\Benutzer\ic-sc\Dokumente\Arduino\libraries\arduino_267956\src/TinyGsmCommon.h:25:0,

                 from D:\Benutzer\ic-sc\Dokumente\Arduino\libraries\arduino_267956\src/TinyGsmClientSIM800.h:21,

                 from D:\Benutzer\ic-sc\Dokumente\Arduino\libraries\arduino_267956\src/TinyGsmClientSIM808.h:12,

                 from D:\Benutzer\ic-sc\Dokumente\Arduino\libraries\arduino_267956\src/TinyGsmClient.h:29,

                 from D:\Benutzer\ic-sc\Dokumente\Arduino\test\test.ino:31:

D:\Benutzer\ic-sc\Dokumente\ArduinoData\packages\esp8266\hardware\esp8266\2.5.0-beta3\cores\esp8266/Client.h:29:21: note: 	virtual int Client::connect(const IPAddress&, uint16_t)

         virtual int connect(CONST IPAddress& ip, uint16_t port) =0;

                     ^

D:\Benutzer\ic-sc\Dokumente\ArduinoData\packages\esp8266\hardware\esp8266\2.5.0-beta3\cores\esp8266/Client.h:37:22: note: 	virtual bool Client::flush(unsigned int)

         virtual bool flush(unsigned int maxWaitMs = 0) = 0;

                      ^

D:\Benutzer\ic-sc\Dokumente\ArduinoData\packages\esp8266\hardware\esp8266\2.5.0-beta3\cores\esp8266/Client.h:38:22: note: 	virtual bool Client::stop(unsigned int)

         virtual bool stop(unsigned int maxWaitMs = 0) = 0;

                      ^

test:68:12: error: cannot declare variable 'http' to be of abstract type 'HttpClient'

 HttpClient http(client, server, port);

            ^

In file included from D:\Benutzer\ic-sc\Dokumente\Arduino\libraries\ArduinoHttpClient\src/ArduinoHttpClient.h:8:0,

                 from D:\Benutzer\ic-sc\Dokumente\Arduino\test\test.ino:32:

D:\Benutzer\ic-sc\Dokumente\Arduino\libraries\ArduinoHttpClient\src/HttpClient.h:41:7: note:   because the following virtual functions are pure within 'HttpClient':

 class HttpClient : public Client

       ^

In file included from D:\Benutzer\ic-sc\Dokumente\Arduino\libraries\arduino_267956\src/TinyGsmCommon.h:25:0,

                 from D:\Benutzer\ic-sc\Dokumente\Arduino\libraries\arduino_267956\src/TinyGsmClientSIM800.h:21,

                 from D:\Benutzer\ic-sc\Dokumente\Arduino\libraries\arduino_267956\src/TinyGsmClientSIM808.h:12,

                 from D:\Benutzer\ic-sc\Dokumente\Arduino\libraries\arduino_267956\src/TinyGsmClient.h:29,

                 from D:\Benutzer\ic-sc\Dokumente\Arduino\test\test.ino:31:

D:\Benutzer\ic-sc\Dokumente\ArduinoData\packages\esp8266\hardware\esp8266\2.5.0-beta3\cores\esp8266/Client.h:29:21: note: 	virtual int Client::connect(const IPAddress&, uint16_t)

         virtual int connect(CONST IPAddress& ip, uint16_t port) =0;

                     ^

D:\Benutzer\ic-sc\Dokumente\ArduinoData\packages\esp8266\hardware\esp8266\2.5.0-beta3\cores\esp8266/Client.h:37:22: note: 	virtual bool Client::flush(unsigned int)

         virtual bool flush(unsigned int maxWaitMs = 0) = 0;

                      ^

D:\Benutzer\ic-sc\Dokumente\ArduinoData\packages\esp8266\hardware\esp8266\2.5.0-beta3\cores\esp8266/Client.h:38:22: note: 	virtual bool Client::stop(unsigned int)

         virtual bool stop(unsigned int maxWaitMs = 0) = 0;

                      ^
````
If i use esp8266 library 4.2.4 (stable) compilation will work fine. so I think, the TinyGSM-library is working.

Arduino-IDE 1.8.8 windows-store Win10-64bit, TinyGSM, ESP8266-2.5.0-beta3 Lolin D1 mini.

### LINKED ISSUE #5749: 2.5.0: Issues with Arduino API
> UDP `virtual IPAddress remoteIP() =0;` `virtual IPAddress remoteIP() const =0;`
you can't change a virtual function in an established Arduino core class

https://github.com/esp8266/Arduino/commit/5c4db3acf4353870b6a5663ba06d712d67e6c179#commitcomment-32254962

> other networking libraries Client implementations do not implement `flush` and `stop` with parameter.
"The type 'UIPClient' must implement the inherited pure virtual method 'Client::stop' "

https://github.com/esp8266/Arduino/commit/83a8076db87b77de6a7b500c18b85057e38ed117#commitcomment-32254941

@jandrassy Can you please give more details ?

Also [If your sketch does not compile and returns error](https://learn.adafruit.com/adafruit-feather-huzzah-esp8266/using-arduino-ide) needs to be addressed.

### LINKED ISSUE #5901: 2.5.0 compatibility issue with Arduino Wire API
The Wire library included in version 2.5.0 breaks compatibility with the common Arduino Wire library.   On version 2.5.0, TwoWire::onReceive() has the following (incompatible) signature:

`void TwoWire::onReceive(void (*)(size_t));`

The expected signature is as follows:

`void TwoWire::onReceive(void (*)(int));`

Portable I2C slave reception code won't compile anymore because of this.

### PR DESCRIPTION
**Pull request by d-a-v**
fixes #5749
fixes #5901 
fixes #5705 
~includes #5997~

### CODE REVIEW

**Comment by d-a-v** [comment]
> Don't have a specific test case, but the changes LGTM. Only possible area of concern is the
> 
> ```
>     void onReceive( void (*)(int) );    // arduino api
>     void onReceive( void (*)(size_t) ); // legacy esp8266 backward compatibility
> ```
> 
> I assume you've done some testing to show this doesn't cause any of the usual type inference errors we seem to have when int-like things and ints are specified as params?

I only made a quick test with `gcc -m32`, assuming `size_t` is `long unsigned int`, a matter of signed / unsigned, and the value is a size, small and always >=0.

**Comment by earlephilhower** [comment]
My own testing this AM shows no problem compiling with the `void cb(int)` and `void cb(size_t)`, so all good for me.

**Comment by jandrassy** [comment]
sorry. why not this way https://www.arduino.cc/en/Reference/EthernetClientSetConnectionTimeout ?

**Comment by d-a-v** [comment]
I don't understand the question. With this PR, Ethernet is not ours anymore.

**Comment by jandrassy** [comment]
> 
> 
> I don't understand the question. With this PR, Ethernet is not ours anymore.
> 
> BTW I opened a PR in ethernet repository so we can use it as a submodule [arduino-libraries/Ethernet#96](https://github.com/arduino-libraries/Ethernet/pull/96)

sorry, maybe this is not the right place. I meant to use setConnectionTimeout for WiFiClient.
